(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val eval : eval_request_src_t:Eval_request_src.t -> Yojson.Safe.t Lwt.t

val get_history : unit -> Yojson.Safe.t Lwt.t

val get_status : unit -> Yojson.Safe.t Lwt.t

val instance_by_name :
  instance_request_name_t:Instance_request_name.t -> Yojson.Safe.t Lwt.t

val instance_by_src :
  instance_request_src_t:Instance_request_src.t -> Yojson.Safe.t Lwt.t

val reset : unit -> Yojson.Safe.t Lwt.t

val shutdown : unit -> Yojson.Safe.t Lwt.t

val verify_by_name :
  verify_request_name_t:Verify_request_name.t -> Yojson.Safe.t Lwt.t

val verify_by_src :
  verify_request_src_t:Verify_request_src.t -> Yojson.Safe.t Lwt.t
