(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    _method: Model_method.t;
} [@@deriving yojson { strict = false }, show ];;

let create (_method : Model_method.t) : t = {
    _method = _method;
}

