(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  vars: string list;
  style: Enums.inductstructuralstyle;
}
[@@deriving yojson { strict = false }, show]

let create (vars : string list) (style : Enums.inductstructuralstyle) : t =
  { vars; style }
