(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = { f_name: string } [@@deriving yojson { strict = false }, show]

let create (f_name : string) : t = { f_name }
