(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  steps: int32 option; [@default None]
  name: string;
  _type: Enums.inducttype;
  body: Method_induct_body_body.t option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create (name : string) (_type : Enums.inducttype) : t =
  { steps = None; name; _type; body = None }
