(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  _type: Enums.inducttype;
  body: Method_induct_body_body.t option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create (_type : Enums.inducttype) : t = { _type; body = None }
