(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    _type: Enums.methodtype;
    body: Method_body.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create (_type : Enums.methodtype) : t = {
    _type = _type;
    body = None;
}

