(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* Name of printer function. Should be of type `t -> string`, where `t` is the type returned by your instance constraint function. *)
  name: string;
  (* Name of the variable in your instance constraint function, e.g. `x` for `fun x -> true`. In an `imandra-repl` session, this is the name of the property on the generated CX module, e.g. the `x` in `CX.x`. *)
  cx_var_name: string;
}
[@@deriving yojson { strict = false }, show]

let create (name : string) (cx_var_name : string) : t = { name; cx_var_name }
