(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  model: Response_model.t option; [@default None]
  _type: Enums.instancetype option; [@default None]
  src: string option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create () : t = { model = None; _type = None; src = None }
