(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    error: string;
    stdout: string option [@default None];
    stderr: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create (error : string) : t = {
    error = error;
    stdout = None;
    stderr = None;
}

