(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  steps: int32;
  bound: int32 option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create (steps : int32) : t = { steps; bound = None }
