(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  steps: int32;
  bound: int32 option; [@default None]
  instance: Response_instance.t;
  unknown_reason: string;
}
[@@deriving yojson { strict = false }, show]

let create (steps : int32) (instance : Response_instance.t)
    (unknown_reason : string) : t =
  { steps; bound = None; instance; unknown_reason }
