(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = { unknown_reason: string } [@@deriving yojson { strict = false }, show]

let create (unknown_reason : string) : t = { unknown_reason }
