(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = { instance: Response_instance.t }
[@@deriving yojson { strict = false }, show]

let create (instance : Response_instance.t) : t = { instance }
